### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1133]
Rolled from #1122.

### Cooking

- [x] add `bookmarks` directory for flexible symlinked bookmarks
- [x] new key <kbd>B</kbd> to add a symlinked bookmark for current dir
- [x] sync multiple instances of `nnn` after operation on selection
- [x] save complete per-context filter when saving sessions
- [x] disable symlink resolution for paths in `NNN_BMS` and arg `PATH`
- [x] do not end selection mode before running plugins/prompt/shell
- [x] plugin `finder` will now retain search filter history
- [x] plugin `bookmarks` removed with symlinked bookmarks support
- [x] list open locations in active contexts in help page
- [x] make option `O_MATCHFLTR` to discard filter key if no match
- [x] configurable `NNN_TMPFILE` to _cd on quit_
- [x] disable auto marking directories (use <kbd>-</kbd>)
- [x] picker mode improvements
  - open tty for input if `STDIN` is non-tty
  - truncate output file before writing
  - do not double select a file on <kbd>Enter</kbd>
- [x] no redraw during du calculation, show only current dir name
- [x] plugin `xdgdefault`: add dmenu support

### Up for grabs

- [ ] notcurses UI backend (#1014) [@KlzXS]
- [ ] open new terminal window in spawned shell dir (#759)

For anything else please discuss in this thread.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**

**Comment by N-R-K** [comment]
Small nitpick, but I think having the ascii logo above the version/license would be better. Reasoning is that the help screen should prioritize showing useful information like keybinding more.

**Comment by jarun** [comment]
Nah. I want to show it off.

**Comment by CantoroMC** [comment]
Hello,
this is are some of my entries for NNN_PLUG 
- e:-!&emacs $nnn
- f:-!&pickOne (this is a zsh script that open a random file with xdg-open)
- d:-!git diff

The first two doesn't work anymore (but they used to); probably something has changed but i'm unable to find the documentation.

**Comment by jarun** [comment]
Please try master. If they do not work, please find the commit that may have broke them. I'm sorry but I don't have the time to find that out for you.

**Comment by CantoroMC** [comment]
I'm on master, it may have happen in the last two days, i will take a look which is the guilty commit and report back.

I've asked to know if plugin syntax have changed without being documented.

**Comment by CantoroMC** [comment]
- https://github.com/jarun/nnn/commit/fa7cef2df75c940994f4a700b317645034864b26 this commits breaks the "plugin" assigned to letter e
- https://github.com/jarun/nnn/commit/27e1eb54c461b2d748ed0f6ed7bb2eaaff2252d4 this commit breaks also the "plugin" assigned to letter f

**Comment by jarun** [comment]
@CantoroMC 

We recently fixed #1162. Can you check that works for you?

**Comment by CantoroMC** [comment]
@jarun 
Yes they work as expected now.

**Comment by jarun** [comment]
Thanks for confirming!

**Comment by CantoroMC** [comment]
As always, thanks to you!

**Comment by CantoroMC** [comment]
Unfortunately, i was wrong.
I've forget to install the new binary and launch the previous one.

**Comment by jarun** [comment]
Make sure you single quote the exports for `NNN_PLUG`.

**Comment by CantoroMC** [comment]
They are already single quotes.

export NNN_PLUG='a:mp3conv;b:oldbigfile;c:fzcd;d:-!git diff;e:-!&emacs $nnn;f:-!&pickOne;g:-!git status;i:imgview;o:fzopen;p:-preview-tui;r:rsynccp;t:-preview-tabbed;x:xdgdefault'

**Comment by jarun** [comment]
Please try to debug this as I will be very busy for a while.

**Comment by jarun** [comment]
@CantoroMC any update on this?

**Comment by CantoroMC** [comment]
Unfortunately, I don't have enough experience/time in order to deal easily with this issue.
As a temporary solution, I have replaced the misbehaving key with actual plugins.
If is required I can help with any feedback/test.

**Comment by jarun** [comment]
@CantoroMC please confirm if commit 046d676a73b70d5c8bd39a5a37866aa75fe70598 fixes the issues.

**Comment by CantoroMC** [comment]
It seems so.
Thanks

**Comment by N-R-K** [comment]
Don't you think the wiki footer should be upgraded from a dolphin to a horse? ♞♘

**Comment by jarun** [comment]
Done! Thanks!

**Comment by pfdint** [comment]
Can we please have rebindable keys? I'm aware it's a somewhat systemic change but we'll have to do it eventually, it's just part of maturing as a program.

**Comment by CantoroMC** [comment]
@pfdint I'm not responsible for the development of nnn and I may be wrong.
I think that what your asking for(configuring keybinding in a config file) is against the nnn philosophy of "No config file, minimal config with sensible defaults"
Anyway, if you don't like the default keybindings(which are very intuitive in my opinion) you can modify https://github.com/jarun/nnn/blob/master/src/nnn.h and compile.

**Comment by pfdint** [comment]
There could be an fff-like option, where keybind overrides are read from environment variables.
(I do find the bindings deficient: three-quarters vim, one-quarter emacs, bunch of rare wacky stuff bound, buttons nearest the fingers being unbound, explanations of the buttons often mystifying; but that's not the point. To fit in to more workflows and for our friends with different keyboards, programs mature into having customizable keys without recompiling.)

**Comment by jarun** [comment]
@pfdint we are not working on a script here. Keybinds can be changed easily if you are OK to compile the program. If not, choose a file manager which suits your needs. There's nothing wrong in that.

**Comment by pfdint** [comment]
Sounds fair.

**Comment by N-R-K** [comment]
> bunch of rare wacky stuff bound
> explanations of the buttons often mystifying

Just out of curiosity, can you name a couple of these rare wacky ones? @pfdint

**Comment by pfdint** [comment]
Definitely the weirdest ones I saw were
] opens a weird interpretive-step-style bash shell
> exports the entire current directory content listing to your editor
0 locks entire terminal with the user password

**Comment by jarun** [comment]
> stands for redirection from the FM to a text file.
0 stands for no access.

] is something taken out of the blue because nothing was available. But `^]` stands for a subshell so you can leave it to muscle memory.

**Comment by N-R-K** [comment]
Idk about the other 2 but `>` is insanely intuitive to a cli user. It's the redirection operator to redirect the output of a command (typically to a file); `echo "something" > to_a_file` 😄

**Comment by jarun** [comment]
In any case, I think @pfdint believes every action available in `nnn` should have a meaningful keybind. There are around 60 of them listed and many have control keybinds. Numbers cannot be used and caps keys need 2 presses. I don't think that expectation is justified.

**Comment by pfdint** [comment]
Rather that every action available should be *able* to be given a meaningful bind. But nnn avoids configurability in favor of pre-configuration, is what I'm understanding. So when that desire is translated to nnn-space, it means pre-configuring every action, which indeed doesn't make much sense.
(We see here one of the reasons it doesn't make sense: after the basics, users will disagree on what bindings are useful, reasonable, and memorable. Having basic vim-bindings invites users to expect more vim-ness, which of course includes capital letters being bound. Capital letters are at most 1.5 keypresses, not two, which is well within comfort range of a vim user. But learning nnn includes throwing that expectation of more vim-ness out, eschewing the capital half of the keyboard in favor of modifier keys. Non-vim users, with no such expectations, might not feel anything missing.)

**Comment by jarun** [comment]
> well within comfort range of a vim user

We never claim that we are vim-like in every aspect. Also, now I remember there was another reason behind the decision to allow users to re-configure only through compilation (note the option `-K` to simplify the process as well). At some point we were spending a significant amount of time on fixing keybind clashes configured by the user.

**Comment by N-R-K** [comment]
Think it's acceptable to disable <kbd>e</kbd> on picker mode? When using `nnn.vim` I've pressed that too many times due to muscle memory resulting in vim being nested inside the vim terminal.

One other problem I've had with the picker mode was <kbd>l</kbd> opening file instead of *picking* them. Using `-o` serves as a *workaround* but in the help screen `l` and `Ret` are listed side by side, so imo the expected behavior is that `l` and `Ret` should do the same thing even in picker mode.

**Comment by jarun** [comment]
> Think it's acceptable to disable e on picker mode?

We can do that.

> One other problem I've had with the picker mode was l opening file instead of picking them.

I think that behaviour is documented in nnn.vim. It was discussed before we left it that way.

**Comment by 0xACE** [comment]
@pfdint Unfortunately we cannot implement that feature for in the state the program is today. E.g. If keybindings were to be implemented it'd make sense to make a config parser first. Instead we lazily rely on environmental variables... I think we are a long way from doing this. Make peace with it and learn to live with it. I agree that some mindings are weird, but I patch them locally and pull my branch to all my machines, I've been disconnected from `master` since day one....

If you insist i wrote you a stupid concept 2 nights ago, beware, not much effort was put into this:
```c
enum action {
	SEL_BACK = 1,
	SEL_OPEN,
	SEL_NAV_IN,
	SEL_NEXT,
};
struct key {
	int sym;
	enum action act;
};



struct key bindings[200] = {
    {'h', SEL_BACK}
};

char *cstr = "65,1;92,3;";

const size_t maxparse = 64;
char keybuffer[maxparse];

int key,act;

char *ptr = cstr;
size_t count = 0;
while(*ptr && sscanf(ptr, "%d,%d;", &key, &act) == 2){
    printf("read: %d,%d\n",key,act);
    bindings[count++] = (struct key){key,act};
    while(*(++ptr)) {
        if (*ptr == ';'){
            ptr++;
            break;
        }
    }
}

```

    read: 65,1
    read: 92,3


It's prone to exploits and would require a bash script that translate the original keystrokes into parseable numbers. It's also require some patching in other parts of the code as `bindings` should actually be a dynamically allocated array, meaning it will lose its sizing information. it could easily be changed to parse `char` too but then you'd have to make sure you apply modifiers correctly and what not...

**Comment by N-R-K** [comment]
@0xACE If they're going to compile from source then at that point might as well just change the binding in the source itself, much less effort that way. `nnn` has very few deps, compiles fast and you can get some extra goodies such as NERD icons, git status etc, I don't see much reason to avoid wanting to compile such a small package.

But anyhow, if not wanting to compile is huge priority then it's probably best to use another FM that allows configurable key-binding. There's a huge list of cli FMs to pick from.

**Comment by 0xACE** [comment]
> @0xACE If they're going to compile from source then at that point might as well just change the binding in the source itself, much less effort that way. `nnn` has very few deps, compiles fast and you can get some extra goodies such as NERD icons, git status etc, I don't see much reason to avoid wanting to compile such a small package.

Yeah, though there are differences of behavior on my different machines. on my phone i use a ipod-esque scrolling behaviour and context aware clicking behavior, i dont remember how i made my android aware of patching this: my nnn branch has been stale for a while now. But other than that all my machines use the same static setup

To make it clear. I wouldn't advocate anyone actually implements a keybind parser, but if he so wishes: a concept has now been provided. **I'm guessing he comes from the usergroup that relies on the distros package manager**. Honestly i rarely ever change upstream keybindings, it makes me agnostic to working on machines that i dont own.

Unrelated to the keybindings: I'll try to go through some of my minor changes that are compatible with upstream and supply patches

**Comment by 0xACE** [comment]
> **I'm guessing he comes from the usergroup that relies on the distros package manager**.

I should emphasize that it translates into: A large group of our (potential) userbase are affected by compile time decisions. Which may hurt our adoption rate.

**Comment by jarun** [comment]
> Which may hurt our adoption rate.

@0xACE I am OK with that. After years of contributing to open source, I have come to realize that the RoI for spending 100s of hours on things that I don't need myself is negligible. _A large group of_ users come back with issues ad the disclaimer that they either can't code or can't compile a program. However harsh it may sound, they should not use the terminal. And it's proven by the fact that Windows is used by > 90% users. We have to accept reality. `nnn` is a niche utility for users who are adventurous. We can't keep spending time fixing/changing trivial things for everyone. My family needs my time more at this point.

Latest example, do you think the guy who wanted `NNN_TMPFILE` to be configurable would be ready to take care of the Homebrew test? NO. I had to spend hours trying dummy ruby code, thinking of workarounds and then deal with unreasonable demands from a downstream packager.

**Comment by luukvbaal** [comment]
It's been a while since I made the change to the patch(juts didn't push it) but it was supposed to improve the git signs representation, not break it.

> when i entered a git directory git "signs" are shown but they will persist, with a pattern that seems random to me, even when i navigate to parent directories.

Could you show a screenrecording of what you mean? I've been using the new patch for the last few months but never encountered something that seems random.

> Previously the left column was dedicated to sign for staged file, now the symbols for untracked (??) and ignored file (!!) are written to the left column (that was not the case with the previous patch)

The new patch indeed tries to show more information about directories when possible, showing both i.e. `?M` when a dir contains bot new files and unstaged modified files. Staging them should change it to `M?`.

**Comment by CantoroMC** [comment]
I post some picture:
I have taken as example the dotfiles directory present in my home folder; starting from the dotfiles directory and pressing `h` will bring my to the home directory.

| dotfiles directory | home directory |
|------------------------|---------------------|
| ![after commit d772223](https://pasteboard.co/YrsmU74I81k3.png) | ![](https://pasteboard.co/2CPhP5JRE9PN.png) |
| ![before](https://pasteboard.co/HnKSsvBIG6xf.png) | ![](https://pasteboard.co/1Iprw9c4Epnp.png) |

**Comment by CantoroMC** [comment]
Home directory is not a git directory so `fatal: not a git repository (or any parent up to mount point /)`
Dotfiles directory 
```
R  deploy/arch-pkgs/bull/fairy-stockfish-bull-git-13.1.r6356.3af1cb67-1-x86_64.pkg.tar.zst -> deploy/arch-pkgs/bull/fairy-stockfish-bull-git-13.1.r6364.edb54396-1-x86_64.pkg.tar.zst
D  deploy/arch-pkgs/bull/neovim-bull-git-0.6.0r19076.270cc1d70-1-x86_64.pkg.tar.zst
A  deploy/arch-pkgs/bull/neovim-bull-git-0.6.0r19175.7f93b2ab0-1-x86_64.pkg.tar.zst
D  deploy/arch-pkgs/bull/nibbler-bull-git-2.1.6.r3288.602ee1c-1-x86_64.pkg.tar.zst
A  deploy/arch-pkgs/bull/nibbler-bull-git-2.1.6.r3314.d6a324b-1-x86_64.pkg.tar.zst
D  deploy/arch-pkgs/bull/nnn-bull-git-4.2.r3683.1723aeb4-1-x86_64.pkg.tar.zst
A  deploy/arch-pkgs/bull/nnn-bull-git-4.2.r3685.e74aa95e-1-x86_64.pkg.tar.zst
R  deploy/arch-pkgs/bull/stockfish-bull-git-14.r5329.21ad356c-1-x86_64.pkg.tar.zst -> deploy/arch-pkgs/bull/stockfish-bull-git-14.r5334.f21a66f7-1-x86_64.pkg.tar.zst
 M deploy/arch-pkgs/makepkg/nnn-git/PKGBUILD
 M neovim/.config/nvim/lua/mc/plugin/picasso/init.lua
M  neovim/.config/nvim/lua/mc/plugin/picasso/themes/srcery.lua
 M neovim/.local/share/nvim/site/spell/dictionary.utf-8.add
 M neovim/.local/share/nvim/site/spell/dictionary.utf-8.add.spl
 M shell/.zshenv
!! deploy/XMonad/Xwm/data/
!! deploy/XMonad/Xwm/dist-newstyle/
!! deploy/arch-pkgs/bull/bull.db
!! deploy/arch-pkgs/bull/bull.db.tar.zst
!! deploy/arch-pkgs/bull/bull.db.tar.zst.old
!! deploy/arch-pkgs/bull/bull.files
!! deploy/arch-pkgs/bull/bull.files.tar.zst
!! deploy/arch-pkgs/bull/bull.files.tar.zst.old
!! shell/.config/zsh/functions/Misc/async.zwc
!! shell/.config/zsh/functions/Prompts/prompt_voidy_setup.zwc
!! shell/.config/zsh/zlib/aliases.zsh.zwc
!! shell/.config/zsh/zlib/functions.zsh.zwc
!! shell/.config/zsh/zlib/navigation.zsh.zwc
!! shell/.config/zsh/zlib/termtitle.zsh.zwc
!! shell/.config/zsh/zlib/vcs.zsh.zwc
!! shell/.config/zsh/zlib/zbell.zsh.zwc
!! shell/.config/zsh/zlib/zcal.zsh.zwc
!! shell/.config/zsh/zlib/zcomple.zsh.zwc
!! shell/.config/zsh/zlib/zkbd.zsh.zwc
!! shell/.config/zsh/zlib/zopts.zsh.zwc
!! shell/.config/zsh/zlib/zplug.d/fzf-tab.zsh.zwc
!! shell/.config/zsh/zlib/zplug.d/zsh-autosuggestions.zsh.zwc
!! shell/.config/zsh/zlib/zplug.d/zsh-history-substring-search.zsh.zwc
!! shell/.config/zsh/zlib/zplug.d/zsh-syntax-highlighting.zsh.zwc
!! shell/.config/zsh/zlib/zplug.zsh.zwc
!! shell/.config/zsh/zlib/zvi.zsh.zwc
```

**Comment by CantoroMC** [comment]
So, I'm right regarding the "persistence" but the second issue is instead a wanted behaviour?

**Comment by luukvbaal** [comment]
I would say so yeah. It's not showing any incorrect information, just more.

**Comment by luukvbaal** [comment]
https://github.com/luukvbaal/nnn/tree/gitstatus seems to fix it. Can you confirm?

Don't quite remember why I changed it in the first place.

**Comment by CantoroMC** [comment]
No more sign in my home directory.

**Comment by jarun** [comment]
Yes, it would lead to downstream issues. Please wait for the next release.

**Comment by jarun** [comment]
Rolled at #1193.
