### ISSUE TITLE
nnn closes previews when a window is opened and closed within same workspace

### ISSUE THREAD

**Issue by ManInTheSuit** [jarun/nnn#1188]
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System: Solus (most recent)
- [ ] Desktop Environment: BSPWM
- [ ] Terminal Emulator: kitty
- [ ] Shell: bash
- [ ] Program options used: U, e, a, alias nnn='nnn -P p' (p:preview-tui)
- [ ] Configuration options set:  
```
# nnn config
[ -n "$NNNLVL" ] && PS1="nnn$NNNLVL $PS1"
export NNN_PLUG='p:preview-tui'
export NNN_FIFO=/tmp/nnn.fifo
export NNN_OPTS="Uea"
export LC_COLLATE="C"
export SPLIT='v'
ACTIVE_PLUGINS="p"
alias nnn='nnn -P $ACTIVE_PLUGINS'
# TODO: use the symlink bookmarks when nnn -v is 4.3

n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # To cd on quit only on ^G, either remove the "export" 
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}


```
#### Exact steps to reproduce the issue

Open kitty. Run ```n``` with above in .bashrc. nnn opens with preview-tui working as expected. Open any new window in same desktop window. Then close it. The preview is gone in the original window

**Comment by luukvbaal** [comment]
Didn't notice this behavior as it was only happening when not using the `-a` flag which is in my `NNN_OPTS`. #1189 should fix it.

**Comment by ManInTheSuit** [comment]
> Didn't notice this behavior as it was only happening when not using the `-a` flag which is in my `NNN_OPTS`. #1189 should fix it.

Thanks, so that patch should fix it? Though I do have a flag in my NNN_OPTS

**Comment by luukvbaal** [comment]
> Thanks, so that patch should fix it? 

Yes, please confirm. 

> Though I do have a flag in my NNN_OPTS

Oh I see, not sure then. I never noticed this behavior but was able to confirm and explain the behavior by the absence of the `-a` flag.

**Comment by ManInTheSuit** [comment]
Thanks, I'll be sure to test it out in new version of nnn, just got 4.3 today with symlink bookmarks

**Comment by N-R-K** [comment]
@ManInTheSuit This was just a change in the plugin. You don't have to wait for new nnn version to use it. Just download the latest preview-tui and replace it in your plugins folder.

**Comment by ManInTheSuit** [comment]
Hmm it seems that the issue is still present, with new preview-tui code.

**Comment by luukvbaal** [comment]
Sorry can't reproduce, can you make a screen recording of the issue?

**Comment by ManInTheSuit** [comment]
https://cdn.discordapp.com/attachments/635625758412505093/894956076963856414/nnn_preview_bug-2021-10-05_16.34.32.mkv

Here's the recording, let me know if you can't access it.

**Comment by ManInTheSuit** [comment]
It happens with other windows for nnn, but it *doesn't* happen with non-nnn kitty splits (e.g. open kitty, split it, open window, close it, split remains)

**Comment by luukvbaal** [comment]
Yeah no I can't reproduce, could you check if it happens with nnn/preview-tui running in another terminal?

**Comment by luukvbaal** [comment]
i.e. with `tmux`

**Comment by ManInTheSuit** [comment]
It does, and only the newest terminal running preview-tui gets affected (previous ones don't, until you close a window directly before/after it).

Surprisingly enough, it doesn't happen in Budgie DE, only happens (that I know of) on BSWPM (maybe related to tiling).
