### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1416]
Rolled from #1348.

### Cooking

- [x] fix <kbd>^N</kbd> not working sometimes (#1449)
- [x] fix file remove confirmation prompt [<kbd>Esc</kbd> - cancel, <kbd>y/Y</kbd> - use force, <kbd>any other key</kbd> - prompt for each file]
- [x] bring back `atool` as the default archive handler
- [x] add option `-B` to use `bsdtar` as the archive utility
- [x] find and list mode improvements
  - continue even if max paths/data size limit is exceeded
  - speed improvements
  - support listing maximum 16K paths of 64 MiB of data
- [x] key <kbd>J</kbd> to jump to an entry or relative offset from current entry

### Up for grabs

None open at the time.

For anything else please discuss in this thread.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**

**Comment by anjerukare** [comment]
Is there option to not display "nnn is already running" when I opened shell in nnn, but to move me to that running nnn.

**Comment by N-R-K** [comment]
> Is there option to not display "nnn is already running" when I opened shell in nnn, but to move me to that running nnn.

Yes, just replace it with `exit`.

```sh
    # Block nesting of nnn in subshells
    [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ] && exit
```

**Comment by anjerukare** [comment]
> > Is there option to not display "nnn is already running" when I opened shell in nnn, but to move me to that running nnn.
> 
> Yes, just replace it with `exit`.
> 
> ```shell
>     # Block nesting of nnn in subshells
>     [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ] && exit
> ```

Thank you! I also added `&> /dev/null` after `exit` to hide output.

**Comment by anjerukare** [comment]
Why does mapping some action to <kbd>Ctrl</kbd> + <kbd>I</kbd> causes a key collision?
I don't see any default mappings on <kbd>Ctrl</kbd> + <kbd>I</kbd> in `nnn.h`.

**Comment by anjerukare** [comment]
Final version of Colemak-DH key binding patches is done.
[colemak-dh-patches_final.tar.gz](https://github.com/jarun/nnn/files/9074261/colemak-dh-patches_final.tar.gz)

#### Changes from [previous version](https://github.com/jarun/nnn/issues/1348#issuecomment-1166299127)
- Return <kbd>v</kbd> to `Move here`
- Set <kbd>k</kbd> to `Manage session`
- Set <kbd>s</kbd> to `Select range/clear`
- Set <kbd>l</kbd> to `Edit sel list`
- Set <kbd>y</kbd> to `Edit file`

#### Summary of changes
<details>
  <summary>Key bindings</summary>
  <br>

  Navigation
  <table>
    <tr>
      <th>Key binding
      <th>Action
    <tr>
      <td><kbd>m</kbd>
      <td>Parent
    <tr>
      <td><kbd>n</kbd>
      <td>Down
    <tr>
      <td><kbd>e</kbd>
      <td>Up
    <tr>
      <td><kbd>i</kbd>
      <td>Open
    <tr>
      <td><kbd>Ctrl</kbd> + <kbd>E</kbd>
      <td>Top
    <tr>
      <td><kbd>Ctrl</kbd> + <kbd>N</kbd>
      <td>End
  </table>
  <br>

  Files
  <table>
    <tr>
      <th>Key binding
      <th>Action
    <tr>
      <td><kbd>s</kbd>
      <td>Select range/clear
    <tr>
      <td><kbd>l</kbd>
      <td>Edit sel list
    <tr>
      <td><kbd>c</kbd>
      <td>Create new/link
    <tr>
      <td><kbd>y</kbd>
      <td>Edit file
  </table>
  <br>

  Other
  <table>
    <tr>
      <th>Key binding
      <th>Action
    <tr>
      <td><kbd>h</kbd>
      <td>Connect remote
    <tr>
      <td><kbd>Ctrl</kbd> + <kbd>F</kbd>
      <td>Toggle type-to-nav
    <tr>
      <td><kbd>k</kbd>
      <td>Manage session
  </table>
</details>

**Comment by jarun** [comment]
@luukvbaal please plan to add to the patch framework. Once you are done, I'll plan for the next release.

**Comment by jarun** [comment]
> Btw, I don't get the point of ${NNNLVL:-0} , we're already making sure it exists with -n $NNN_LVL. @jarun

@N-R-K sorry I missed earlier. Yes, I think it's redundant.

**Comment by jarun** [comment]
@N-R-K please confirm commit 33a74d46f99e29f193ca759843c6c97ef216dd6e.

**Comment by jarun** [comment]
@N-R-K please confirm commit f4f4e1a97b7539f5dcd21eb07c6284b6153b1c3f. This is the latest version.

**Comment by ismozz** [comment]
thanks.

[ISMOZ.COM](https://www.ismoz.com/)

**Comment by jarun** [comment]
> Any good reasoning against fzy?

It's a dead tool - https://github.com/jhawthorn/fzy/issues/135

**Comment by vaygr** [comment]
I'm not sure a couple of feature requests not addressed within a few months is enough to mark it dead. I, for instance, have software that was updated more than 15 years ago, but it still works as expected and is unlikely to get any more updates. Another good example is bspwm, which is pretty slow in terms of bug and feature requests handling with the last release 2 years ago, but it's not going anywhere.

Another thing, nobody discarded forks – so some might have it built for themselves with specific changes they need, while for most users it'd good enough. And if the community decides a lot of things piled up with no movement for a long time, it will be eventually forked – that's how recently nsxiv popped up.

And it seems there are some good PRs coming up (https://github.com/jhawthorn/fzy/pull/170, https://github.com/jhawthorn/fzy/pull/174) meaning people still need and use this tool.

So I don't think this argument is strong enough.

I personally prefer a compact 39K binary over 2.5M bloated one for the job I need, and have no interest in keeping the entire Go toolkit when building packages from source (since I use a source-based distro as well).

I think it would be great to have alternative fuzzy searchers to challenge the status quo, but also for extensiveness and overall health of nnn providing users choice of functionality implementations (like mediainfo, exiftool, file for filetypes/fileinfo).

**Comment by jarun** [comment]
@vaygr I have a problem with a maintainer not even responding to feature requests. Period.

**Comment by N-R-K** [comment]
@vaygr We get bug reports on plugins quite often which are actually upstream issues. So if a particular upstream is unmaintained and/or doesn't respond on defect reports, then I can understand why @jarun may not want to have that project be included in the plugins.

Besides, plugins are indicative so you're free to modify them to support alternatives. And you can make your modifications public as well so that other's who are interested can fetch from that.

**Comment by jarun** [comment]
@vaygr I don't want to have deps on repos which are unresponsive. Write your own plugin and move on. No one cared when I removed `fzy` (including its maintainer). That's exactly where it's popularity lies.

**Comment by N-R-K** [comment]
Does anyone actually use `icons-in-terminal` ? I'm thinking of removing it.

**Comment by anjerukare** [comment]
Is it possible to set up archive extraction to open extracted folder in the current context?

**Comment by jarun** [comment]
No, don't want to change the behaviour. But extract to `.` and a new context will not be opened. Thanks!

**Comment by egrain** [comment]
Is there a way to do nnn -A inside nnn? 
I'm sure there is a reason to make the auto advance thing the default, but I hate it.

**Comment by N-R-K** [comment]
@egrain you can use `NNN_OPTS` to set `A` to be default. See the manpage for more details.

**Comment by tzeikob** [comment]
Not sure if anyone has already mentioned this, but in the case where trash is enabled wouldn't be better to have the key binding `x` attached to trash and the `ctrl + x` to the rm command so we can have both ops? Now both bindings set to trash if trash environment variable is set. Kind of the way the GUI file managers work (delete, shift + delete) nowadays.

I'll be happy to work on this.

**Comment by jarun** [comment]
No, I don't want the keybind to percolate that deep. An additional check at every step makes the code unmaintainable at some point.

TBH, we don't want to become like the other file managers in every aspect.

**Comment by jarun** [comment]
@N-R-K @luukvbaal what do you guys say?

**Comment by N-R-K** [comment]
You can already use a plugin for doing `rm`, bind it to `x` and then use <kbd>alt+x</kbd> for doing deletion bypassing `NNN_TRASH`. So yes, I agree with @jarun that there's no need to modify nnn for this.

**Comment by tzeikob** [comment]
@N-R-K you're totally right, I was about to follow up with this solution too!

**Comment by jarun** [comment]
In general, the `Ctrl` keybind variant is for users who prefer the _type-to-nav_ mode. This type of change will violate that.

**Comment by ouuan** [comment]
I read the #1386 thread but I don't understand why [the `.` problem (smart parent directory)](https://github.com/jarun/nnn/pull/1386#issuecomment-1149101603) did not prevent the patch from being merged or how to solve this problem. How am I supposed to get the `.` behavior now?

**Comment by jarun** [comment]
What is the `.` behaviour? What tool do you want to use?

**Comment by ouuan** [comment]
> What is the `.` behaviour? What tool do you want to use?

I've linked to [your comment](https://github.com/jarun/nnn/pull/1386#issuecomment-1149101603). [You said "With atool I just use `.` and it works"](https://github.com/jarun/nnn/pull/1386#issuecomment-1149118671) so I used the word "`.` behavior".

I want to use `atool`, but now the default one is `bsdtar`.

**Comment by jarun** [comment]
Uninstall bsdtar and you should be fine.

**Comment by ouuan** [comment]
> Uninstall bsdtar and you should be fine.

I'm using Arch, `bsdtar` is a part of `libarchive`, and `libarchive` is required by many packages including the package manager `pacman`.

**Comment by thenoobtester** [comment]
Hi, great file manager ! 

Is there any chance you could integrate fribidi? I ask because I regularly work with a bunch of files with names in arabic and it would make it easier for me to read them. I usually just pipe the output of commands (e.g ls or cat) to fribidi but in this case it doesn't work. It would be great but not urgent. 

Thank you

**Comment by jarun** [comment]
@thenoobtester I am not familiar with fribidi. However, I don't see why it needs integration? It should work like any other font, right?

**Comment by jarun** [comment]
@ouuan reverted at b76cea3a341fbb1d1525efb942cb73fa9fc03c0d.

**Comment by 0xACE** [comment]
@thenoobtester it seems like it would be trivial to add fribidi support.

You would need to patch `dentfill` and `SEL_RENAME` to use `fribidi`'s visual strings.

If the `dentfill` change slows things down too much (unlikely) you could add the visual string to the associated structure.
