### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1537]
Rolled from #1454.

### Cooking

- [x] create new file or directory (tree) on startup
- [x] improve archive, rename and create new workflows
- [x] optimize link creation
- [x] allow overwriting regular files on new empty file creation
- [x] add correct check for Wayland in clipboard plugins

### Up for grabs

None open at the time.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**

**Comment by 875d** [comment]
does the wiki says that without atool, pressing enter on an archive opens it with the opener, and with atool instead pressing enter will show options?

**Comment by jarun** [comment]
When atool is not available default opener is used. atool/bsdtar are optional.

**Comment by 875d** [comment]
> When atool is not available default opener is used. atool/bsdtar are optional.

That's not the question.

The question is:

**does the wiki says that** without atool, pressing enter on an archive opens it with the opener, and with atool instead pressing enter will show options?

**Comment by jarun** [comment]
See https://github.com/jarun/nnn/wiki/Usage#dependencies

It's doesn't have to. The system default opener invokes a tool which `nnn` is not aware of and can't know which options would be provided.

**Comment by 875d** [comment]
> The system default opener invokes a tool which nnn is not aware of and can't know which options would be provided.

I didn't say nnn should know which options the software called by the opener provides.

I said that the wiki should say that, if you hover over a file with an extensions that matches `NNN_ARCHIVE`,
- If `atool` is available, options to open/extract/mount the archive are provided
- If `atool` is not available, the opener is called

> It's doesn't have to

The wiki doesn't have to document the behavior of `nnn` when an archive is hovered on? Even when that behavior changes on the basis of the software installed on the system?

**Comment by jarun** [comment]
> Even when that behavior changes on the basis of the software installed on the system?

Exactly. When the _optional_ tool is not present, the default behaviour is to call the opener. Otherwise, if the user chooses an option, what would `nnn` do?

**Comment by 875d** [comment]
> Exactly. When the optional tool is not present, the default behaviour is to call the opener. Otherwise, if nnn shows the options and the user chooses an option, what would nnn do?

Carry the option chose by the user?

I don't see how that answer my objection.

The objection is: **the wiki** should say that:

> if you hover over a file with an extensions that matches NNN_ARCHIVE,
>
>    If THE OPTIONAL NOT COMPULSORY atool is available, options to open/extract/mount the archive are provided
>    If atool is not available, the opener is called

Even if atool is optional, the wiki still should say that the bahvior changes when the optional tool will change the behavior of nnn.

I didn't have atool installed. I hovered over an archive and pressed Enter. (I think) the opener was called on that file since it got opened in GNOME Archive.

Then I went to the wiki and looked on how to extract archives with `nnn` and couldn't find exactly how (except that `atool` is an optional dependencies, but it doesn't say what happens when it is available).

Then I googled it and found [this](https://www.reddit.com/r/commandline/comments/f6sbkz/underused_power_features_of_file_manager_nnn/).

It said that by pressing Enter on the archive `nnn` would have show you options. It didn't for me.

Since the poster said "I have atool", I *guessed* that the behavior would change with atool installed.

So I installed it and it did.

I think that this behavior should be documented, I should not have googled it (only look for it in the wiki) and I should not had to guess it.

This doesn't imply in any way shape or form that atool should be compulsory.

**Comment by 875d** [comment]
> Otherwise, if nnn shows the options and the user chooses an option, what would nnn do?

I don't understand why you keep talking about the software. I'm talking about the wiki, not about the software.

**Comment by jarun** [comment]
> I'm talking about the wiki, not about the software.

OK. So you want it to be documented in the wiki. Where and what should be the content?

**Comment by 875d** [comment]
Maybe under [Basic use cases](https://github.com/jarun/nnn/wiki/Basic-use-cases#the-nnn-magic) create a new section "Manage archives".

- A file whose extension matches one of the extensions provided in `NNN_ARCHIVE`, is an *archive*.
- If you hover over an *archive* and press Enter:
    - If atool or bsdtar is available, options to 'o'pen/e'x'tract/'l's and 'm'ount the archive are provided
    - If both of the are available [atool/bstar] take precedence
    - If neither of them are available, `nnn` will try to open the file with `NNN_OPENER`

**Comment by jarun** [comment]
It says very clearly in the [Depedencies](https://github.com/jarun/nnn/wiki/Usage#dependencies) section that:

    tar, (un)zip [bsdtar/atool/(un)rar for more formats]

And then in the [Configuration](https://github.com/jarun/nnn/wiki/Usage#configuration) section that:

```
3. With atool or bsdtar and (un)rar installed you can have:

export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
```

Your problem is you have defined `NNN_ARCHIVE` but didn't install any optional utility to handle it.

**Comment by jarun** [comment]
Even without `atool`, if you have `unzip` installed, pressing Enter on it would show the prompt. It's pretty basic:

If you do not have the utility to handle a specific archive type, the default opener will be invoked.

**Comment by N-R-K** [comment]
That behavior is documented in the manpage as far as I can see:

```
     NNN_ARCHIVE: archive extensions to be handled silently (default: bzip2, (g)zip, tar).

         export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"

         NOTE: Non-default formats may require a third-party utility.
```

**Comment by amalgame21** [comment]
calm down

**Comment by rieje** [comment]
Anyone know what binding triggers the behavior that when opening the file, the cursor moves to the next item? Really annoying I toggle that by accident but not sure what key to toggle it back so I need to restart the instance.

**Comment by jarun** [comment]
The program help shows with `?`. It's there:

    ^J  Toggle auto-advance on open

**Comment by 875d** [comment]
1. Switch to select only folders (hide files)
2. Switch to deactivate selection of multiple files/folders
3. Switch to support a user-provided name for new files
Use case: use nnn as file chooser for through https://github.com/GermainZ/xdg-desktop-portal-termfilechooser

**Comment by jarun** [comment]
Check the picker mode. Option `-p`.

1. Folders are always on the top and clearly visible with customizable color. You can select the folders and press `Q` to exit. The selection will be printed. You can also use option `-p` to print the selection to an output file.
2. Use the picker mode, select what you want and quit.
3. `nnn` can't start with non-existent files. It's not vim. You can create a new file in `nnn` using `n`.
4. Open the file to read it. Creating a new file would fail if the file exists.

**Comment by 875d** [comment]
1. I know about picker mode. I didn't know that you can *select* folders (i.e., pressing `Space` over them), and by quitting `nnn` the selection will be written in the file provided by `-p`. Since both `Q` and `q` seems to work in this case, what is the difference between the two? I used to hover over a file and press `Enter` (with the `-p` option, it will write the file path to that file)
2. It is still useful to know whether the website can accept multiple files or only one file is accepted
3. But the browser is providing a "default" filename for the file to save, which is useful to have. I think we can have a switch that set the default filename in readline when you create a new file?
4. Seems reasonable at the moment

**Comment by raffaem** [comment]
I made a fork of xdg-desktop-portal-termfilechooser that allows that allows a FileChooser portal with `nnn` [here](https://github.com/raffaem/xdg-desktop-portal-termfilechooser)

**Comment by jarun** [comment]
@raffaem how does it handle the workflow of browser suggesting the default filename for the file to save?

**Comment by raffaem** [comment]
> @raffaem how does it handle the workflow of browser suggesting the default filename for the file to save?

It separates the dir from the filename. The dir is opened in nnn, and the filename is copied to the system clipboard.

**Comment by jarun** [comment]
Awesome!

**Comment by luukvbaal** [comment]
The way this is usually done, including the wiki example we already have, is to create an empty file with the suggested name which can be selected immediately.

**Comment by raffaem** [comment]
> The way this is usually done, including the wiki example we already have, is to create an empty file with the suggested name which can be selected immediately.

But then you have to manually delete the file if you want to save to another name.

And you are stuck with it if you forget to delete it.

Maybe have an option that pass the default name to readline?

**Comment by jarun** [comment]
> Maybe have an option that pass the default name to readline?

The major problem is it percolates deep down and through several checks. And then there are the cases of overwrite, cancellation and so on. The current arrangement seems to be the best to me.

**Comment by luukvbaal** [comment]
You can simply delete the suggested file if it is still empty when nnn closes (which is what the wiki example does).

**Comment by raffaem** [comment]
> You can simply delete the suggested file if it is still empty when nnn closes (which is what the wiki example does).

Oh, I see.

What if the folder has a lot of files? How do you find which file to select, if you want to save in the default position?

**Comment by luukvbaal** [comment]
Pass the suggested file as argument to nnn and nnn will place the cursor there on startup.

**Comment by raffaem** [comment]
> Pass the suggested file as argument to nnn and nnn will place the cursor there on startup.

That makes sense.

Is [this one](https://github.com/jarun/nnn/wiki/Basic-use-cases#file-picker) the wiki entry you are referring to?

**Comment by luukvbaal** [comment]
https://github.com/jarun/nnn/wiki/Advanced-use-cases#firefox

**Comment by jarun** [comment]
At commit 56d6c8e674d9e25f97cfbe01a2f800f75532ac12 I have made a change to allow overwriting existing regular files on new file creation.

**Comment by jarun** [comment]
This may not help immediately but I am thinking of options to allow creation of non existent files on passing the option at startup.

**Comment by raffaem** [comment]
All right, I finished the work on my form for now.

I implemented the suggested workflow (touching a new file on save and deleting it afterwards if it's empty).

Also my fork should now work out-of-the-box: just install it and change the configuration file.

> See commit [56fd6ea](https://github.com/jarun/nnn/commit/56fd6eac657a4c8d0c8ab2d9bad1c73d39013107) for an implementation of creating a new file at startup.
> 
> Note that the parent directory, if passed, much exist and has to be accessible. Otherwise `nnn` will quit.
> 
> I implemented it because I see a faster workflow where I can just `nnn new.txt` and create and start using the file from within `nnn`.

Thanks, I will take a look at it.

**Comment by jarun** [comment]
Lifted all restrictions at commit d4c3e52f2f555d9960bdb59681ea6c7978ff3b03. `nnn` will attempt to create non-existent directory trees, directory-only paths can also be created (more in the man page).

**Comment by raffaem** [comment]
Following the latest commit, I have removed the creation of file from the wrapper and now I delegate all to nnn.

But there is something that makes me uncomfortable with this implementation.

1. What is the workflow in case I want to save the file in a different folder than the suggested one? I first save in the suggested one, and then move the file around?

2. When I put a path in front of the suggested file name (e.g. I'm in `~/Download`, the suggested file name is `file.pdf`, and I put `../Documents/file.pdf`, and suppose that `../Documents` doesn't exist), the full tree is effectively created if it doesn't exist, but then the file is not selected (i.e., the folder is not changed). Would it make sense to select the file also in this cases?

**Comment by jarun** [comment]
1. It's optional to use. You can still use the older older technique:

> It separates the dir from the filename. The dir is opened in nnn, and the filename is copied to the system clipboard.

Otherwise, you can pass the complete tree as well. `nnn` will create the directories and prompt with the filename.

2. I don;t understand. On master, it prompts with the suggested filename and when you create it, the new file is selected.

**Comment by raffaem** [comment]
2. 

Suppose neither `~/Documents/file.pdf` exist nor `~/Download/file.pdf` exist

Call `nnn ~/Documents/file.pdf`. Remove all text, type `../Download/file.pdf` and press enter. `nnn` will not switch to the folder.

**Comment by jarun** [comment]
Yes, that is the correct behaviour as of now. The file is being created in another directory. In a regular workflow, the user may not want to switch to  the other directory yet, hence she didn't switch first and then create.

I will think more on this.

**Comment by 875d** [comment]
> Yes, that is the correct behaviour as of now. The file is being created in another directory. In a regular workflow, the user may not want to switch to the other directory yet, hence she didn't switch first and then create.
> 
> I will think more on this.

But can you switch first if readline is waiting for the input?

If we can implement navigation while readline is waiting for user input that would be perfect

**Comment by jarun** [comment]
No we can't.

**Comment by jarun** [comment]
@raffaem I think your previous wrokflow is better - open the default and copy the filename to clipboard. I don't want to over-complicate things here.

**Comment by KlzXS** [comment]
@jarun How vigilant do we want to be with what is considered a dependency for plugins? The list is a bit inconsistent and I'm not exactly sure what should and shouldn't be considered a dependency.

**Comment by jarun** [comment]
Generally speaking, the base utilities installed by default OR which are well-known are left out.
