### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1546]
Rolled from #1537.

### Cooking

- [x] create new file or directory (tree) on startup
- [x] improve archive, rename and create new workflows
- [x] optimize link creation
- [x] allow overwriting regular files on new empty file creation
- [x] add correct check for Wayland in clipboard plugins

### Up for grabs

None open at the time.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**
