### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#202]
Rolled from #137.

### Proposed and completed features

- [ ] draw help screen in a scrollable window/pad
- [ ] support command completion with libreadline
- [ ] support soft delete to _reclycle bin_
- [ ] vertical split pane (discussion required)
- [ ] compile with PDCurses
- [x] make libreadline an optional dep
- [x] use `nnn` as a file picker with [picker.sh](https://github.com/jarun/nnn/blob/master/user-scripts/picker.sh)
- [x] user-contributed scripts [repository](https://github.com/jarun/nnn/tree/master/user-scripts)
- [x] substring search for filters (option `-s`)
- [x] version sort (option `-n`)
- [x] disk usage calculation abort with <kbd>^C</kbd>
- [x] create sym/hard link(s) to files in selection
- [x] archiving of selection
- [x] show dir symlinks along with dirs on top
- [x] key `N` (1 <= N <= 4) to switch to context N
- [x] bring back `NNN_OPENER` to specify file opener
- [x] env var `NNN_NOTE` and keybind <kbd>^N</kbd> for quick notes
- [x] handle multiple arguments in VISUAL/EDITOR
- [x] show the current directory being scanned in `du` mode
- [x] select all files
- [x] use libreadline for command prompt
- [x] reduce delay on <kbd>Esc</kbd> press
- [x] config option to avoid unexpected behaviour on 0-byte file open (see #187)
- [x] support custom opener (e.g. `mimeopen`)
- [x] run a command (or launch an application)
- [x] a new demo video (see #167) (thanks @Kallinteris-Andreas)
- [x] choose script to run from a script directory (see #127)
- [x] shortcut to run current file as script
- [x] support a _combined_ set of arguments to `$EDITOR`, `$PAGER` and `$SHELL`
- [x] remote connection and file transfers (using lftp)
- [x] per-context directory color
- [x] support for Cygwin env
- [x] offer to `fore` file removal
- [x] support selection across directories and contexts
- [x] parse EDITOR or VISUAL for options when `NNN_USE_EDITOR` is set
- [x] option to disable file open on navigation (Right Arrow and `l` keys)
- [x] vim plugin to use `nnn` as a file picker within vim
- [x] retire `nlay` (no more used by `nnn`)
- [x] integrate static analysis on Travis
- [x] list currently copied files
- [x] option to disable directory auto-select
- [x] use `$TMPDIR` if available
- [x] support terminal locking on OS X (bashlock) and BSD (lock)
- [x] support `patool`
- [x] run any number of scripts
- [x] prefer VISUAL over EDITOR
- [x] add a keybind to run a custom script (see #79)
- [x] integer `get_coolsize()` (thanks @arsv)
- [x] batch rename, move, delete files with vidir integration
- [x] copy file paths when X is unavailable
- [x] support copying multiple file names to copier
- [x] add open with... shortcut
- [x] add option to open bookmark directly
- [x] optimize memory usage and algorithms for file name handling
- [x] list and extract archives
- [x] show current selection number along with total entries in dir
- [x] support `NNN_NOWAIT` to unblock nnn (DE specific)
- [x] file and directory creation
- [x] change to light mode if number of cols < 35
- [x] in-place file rename
- [x] watch out for current dir changes (if not in filter or du mode)
- [x] pin and jump to a directory
- [x] show vol capacity and vol free in help
- [x] option to use exiftool instead of mediainfo
- [x] option to show dirs in custom color (default: enabled in blue)
- [x] show dir content size and number of files in du mode
- [x] support bookmarks string
- [x] add option to support opening text files in EDITOR
- [x] use `xdg-open` on Linux and `open(1)` on OS X as desktop opener
- [x] support multiple apps in `nlay`
- [x] use `vlock` as default terminal screensaver
- [x] *navigate-as-you-type* mode
- [x] subtree search (using gnome-search-tool or catfish)
- [x] support custom nlay
- [x] *search-as-you-type* at filter prompt
- [x] RPM packages for RHEL/CentOS (thanks @fennm)
- [x] ~support cd ..... (with . as PWD, stops at /)~ (feature removed)
- [x] jump to initial directory (where nnn was started)
- [x] `nlay` - a shell script for actions like open desktop search utility, run screensaver
- [x] show file details, mediainfo output, help in `less`
- [x] show media information (needs mediainfo)
- [x] use `Q` to quit to current dir (needs external shell integration)
- [x] use `^Q` to quit (even from filter mode)
- [x] UTF-8 support
- [x] add option to start in disk usage analyzer mode
- [x] open current dir in desktop file manager
- [x] disk usage analyzer more
- [x] show unprivileged free blocks in du mode
- [x] shortcut `-` to jump to last directory
- [x] ~resolve `~` (HOME) at chdir prompt~ (feature removed)
- [x] option to show complete stats of just the current entry (name, file type, human readable permission string, byte size... all `lstat()` details)
- [x] update noice man page
- [x] sort entries by size
- [x] support file path copier script (`NNN_COPIER`)
- [x] support detail view (default)
  - [x] file type
  - [x] modification time
  - [x] human-readable file size
  - [x] current item in reverse video
  - [x] full name of currently selected file in bottom "bar"
- [x] roll navigation with `Up` and `Down` at the first and last entries
- [x] remove restriction on visiting parent dir when opened with a relative dir path
- [x] case insensitive alphabetic content listing
- [x] generate optimized binary
- [ ] ~show total number of files in du mode~ (apparently it has to be counted in nftw callback, with adjustments like file type check, hardlink check, which means unreasonable overhead)
- [ ] ~threaded/multicore nftw(3)~ (overkill, we are already very fast)
- [ ] ~use scandir instead of readdir~ (we are using custom alphanum sort, see https://github.com/jarun/nnn/commit/691291245a88d1c2277d8900a13f41b00685a72c)
- [ ] ~modify packagecore.yml and probably Makefile to generate OpenSUSE Leap package~

Anything else which would add value (please discuss in this thread)

**Comment by jarun** [comment]
Simply awesome! I had been looking for a concise listing to save memory. :+1: Many thanks! 

> I think archiving should apply to selection

The problem is the archiver is third party utility and not each one follows the same syntax. And then passing a variable list to `exec()` is trouble. So the use case now we have is to _select_ the files, copy/move them to a dir and archive that dir.

> Right now, I use Ctrl-u after filtering with / before I can use <h,j,k,l>

Instead of `Ctrl-U` you can press `Esc` to escape the filter prompt.

> it happens only at the first time

I will check this. I can reproduce it.

**Comment by jarun** [comment]
I think some entries are missing e.g., ^K. Also, now I am myself finding it difficult to figure out a key from the list. Everything seems too close for comfort. :(

**Comment by jarun** [comment]
The 3rd issue should be fixed at 5df231947392475ced257a6ba5e4cec3c3fbb5a9.

**Comment by jarun** [comment]
The 3rd issue should be fixed at commit 81318f9218adaeae3044d1d93ee4700cb056752d.

**Comment by lawnowner** [comment]
> The 3rd issue should be fixed at commit 81318f9.

Yes!

> So the use case now we have is to select the files, copy/move them to a dir and archive that dir.

This does the job just as good, thanks.

> I think some entries are missing e.g., ^K. Also, now I am myself finding it difficult to figure out a key from the list. Everything seems too close for comfort. :(

Yeah, I omitted four shortcuts, picked only one when there are alternatives, and used my usual dense notation; easier for me to commit to memory this way, but bad for documentation :] I just put it here so that maybe some other people benefit.

> Instead of Ctrl-U you can press Esc to escape the filter prompt.

When I press `Esc` at the filter prompt, the filtered list is lost, i.e. the list goes back to the unfiltered state. I think after typing /pattern at the filter prompt, pressing `Enter` should go back to navigation so that `<h,j,k,l>` can be used.

**Comment by jarun** [comment]
> pressing Enter should go back

I might be missing something... pressing Enter always opened the file or dir... even in filter mode.

**Comment by lawnowner** [comment]
Just checked, and indeed `Enter` opens the entry in v1.6; I remembered its behaviour was exiting the filter prompt because the entries I tried in the past were all files and there wasn't programs associated with their mimetypes on that system. Now that aside, `<h,j,k,l>` navigation in a filtered list should be possible I think. Right now I can only use arrows, or `Ctrl-u` to leave the filter prompt before `<h,j,k,l>` navigation works, because `Esc` cancels filter.

**Comment by jarun** [comment]
When you press h/j/k/l that becomes a part of the filter string. So pressing any of up/down arrow is the way to do this.

**Comment by lawnowner** [comment]
Alright then. Although `Ctrl-u` is a bit of a hack, there is an alternative to arrows that is closer to the home row. Thanks.

**Comment by jarun** [comment]
Yes, the keyboards/keypads differ among form factors so it's really a difficult call to favour one against the other. I generally try to keep things easier for the Termux users on Hacker's keyboard (I am one of them). For regular keyboard users, life is much simpler.

**Comment by jarun** [comment]
BTW, I have made the help a little more concise now without sacrificing visibility... space is the separator now and I could reduce a column of text.

**Comment by jarun** [comment]
@lawnowner archive selection is available at commit d9977c5ea1c4401f2d7981ba30baeda8aa4015a3.

**Comment by zQueal** [comment]
Any chance of seeing a Windows variant? There are some locations where I'm required to use Windows, and of course I use Vim for convenience. I'd like to switch to `nnn`, but for it to only be available part of the time is a hurdle.

**Comment by zQueal** [comment]
> You can use nnn on Cygwin and Linux subsystem for Windows.

Cygwin is pretty cancerous, and working with LSW is more of a pain than just not using Vim.

I'll attempt the native option.

Thanks!

**Comment by jarun** [comment]
That would be great! Please let me know if you need any help.

**Comment by Garzet** [comment]
I love `nnn`, but comming from `ranger` I miss better sorting by name when there are numbers in the name. I often name my files like so:
- `abc 1`
- `abc 2`
- `abc 10`
`nnn` sorts it like so:
- `abc 1`
- `abc 10`
- `abc 2`
Ranger would sort this the way I expect (1, 2, 10). The same is true when file name starts with numbers but does not **only** contain numbers (i.e. `1 abc`). I could change my file naming habits and start naming files with leading zeroes, but I would rather not :)
Is there a reason why numeric sort only works when filename contains only numbers?

**Comment by jarun** [comment]
> The same wrong sorting

It's implemented that way. Only pure-numeric names are sorted in numeric order.

> Is there a reason why numeric sort only works when filename contains only numbers?

Take a look at issue #190.

I see the following problems:

1. The version sort is probably slower. Let's say we want to compare `abc 10` and `abc 2`. `strcoll()` would compare 5 characters each but `strverscmp()` would also check the last character in the first string. `nnn` strives for speed. When you are having a directory of 10000 similar files this overhead is significant.

2. The other problem is `strverscmp()` is non-portable. We can, however, bypass that. The source code is available:
 - https://github.com/lattera/glibc/blob/master/string/strverscmp.c
 - https://code.woboq.org/userspace/glibc/string/strverscmp.c.html
 - https://android.googlesource.com/platform/external/bison/+/android-4.4_r1/lib/strverscmp.c

3. `strverscmp()` places capitals on top. We really don't want that. No one remembers if a file name starts with `a` or `A`.

**Comment by DavideSilva** [comment]
Any chance of adding the comma key to be a Leader key? The current options are impossible to use for those of us who do not have an US keyboard layout.

**Comment by jarun** [comment]
@DavideSilva sure thing! Could you kindly raise a PR? Please feel free to ask if you need any help.

**Comment by DavideSilva** [comment]
I was but now that I tried the master version, I think my need for adding the comma key as leader as disappeared. My motivation was to be able to switch contexts but that will be possible using the 1-4 keys.

I've only just found this so I'm not at all familiar with all the features `nnn` has but from the help menu I can only see the Leader key being used to create/switch contexts.

@jarun Do you think it is still worth it to had the comma key as a Leader?

**Comment by jarun** [comment]
We have two keys mapped to leader - `^/` and ```. Do you have the second one (backquote) in your keyboard?

**Comment by breisa** [comment]
I don't know what keyboard layout @DavideSilva is using, but for example on a [german keyboard](https://upload.wikimedia.org/wikipedia/commons/3/36/KB_Germany.svg) the current leader-number combinations are impossible too. There are <kbd>/</kbd> and <kbd>`</kbd> keys, but to get them you have to press <kbd>Shift</kbd> wich prevents you from entering a number at the same time. (e.g. <kbd>Shift</kbd> + <kbd>4</kbd> = <kbd>$</kbd>)
A leader key that is accessible without pressing a modifierer key would be a better choice. Examples for such a key in the german keyboard layout would be: <kbd>+</kbd> <kbd>-</kbd> <kbd>.</kbd> <kbd>,</kbd> <kbd>\<</kbd> <kbd>´</kbd> <kbd>^</kbd> <kbd>#</kbd>

**Comment by jarun** [comment]
<kbd>,</kbd> it is! ;)

**Comment by jarun** [comment]
@Garzet version sort is in on master! Please let me know how it goes.

**Comment by jarun** [comment]
@DavideSilva & @breisa comma replaces backquote as leader key at commit f21ec611cd648d7a340a7d02ad442a4fa7ac96c4.

Have multiple contexts open and try comma comma, comma dot. ;)

**Comment by breisa** [comment]
@jarun Thank you, works like a charm. :+1:

**Comment by jarun** [comment]
@breisa awesome!

**Comment by Garzet** [comment]
> @Garzet version sort is in on master at commit [336eca3](https://github.com/jarun/nnn/commit/336eca300a3ed466172b1ca67bc610f230267053)! Please let me know how it goes.
Works perfectly! Thanks!

**Comment by jarun** [comment]
Thanks for the try!

**Comment by norcalli** [comment]
@jarun something to consider is the `atool` utility for archives, which already does the work of trying to monomorphize the interface to interacting with archives. http://www.nongnu.org/atool/

Also, I'm interested in perhaps adding support for ssh browsing, but my C is a bit rusty, so it might be a while.

**Comment by jarun** [comment]
`nnn` works with `atool` / `patool` already - https://github.com/jarun/nnn#utility-dependencies.

`lftp` is my preferred way to go for remote transfers - https://github.com/jarun/nnn/wiki/simplify-remote-transfers-with-lftp

**Comment by amosbird** [comment]
Does `support file picker mode` mean a file chooser similar in GTK and QT?

**Comment by jarun** [comment]
@amosbird in picker mode, `nnn` opens and you can select one or multiple files.

**Comment by amosbird** [comment]
Is it possible to act as a file dialog and possibly replace the Gtk/Qt ones system-widely

**Comment by jarun** [comment]
Nope.

**Comment by maciejsum** [comment]
Hi, I'm about to switch from ranger, but the way quit-and-cd is implemented bothers me: I often forget to press `C-g` and press `q` instead. Wouldn't it be more convenient to always update `$NNN_TMPFILE` on quit? (Of course if the environment variable is set.) I mean, if I want to change the directory, I have to call `nnn` through a special Bash function (that sources $NNN_TMPFILE afterwards) anyway, so additionally telling `nnn` about this fact seems redundant to me.

**Comment by jarun** [comment]
> Of course if the environment variable is set.

`$NNN_TMPFILE` specifies the tmp file where `nnn` should write the last visited dir **if the user chooses to cd n quit** and NOT the other way around.

The intention of the user is confirmed by <kbd>^G</kbd>. In no way it means the user **always wants to drop into the last visited directory on quit**.

Don't add your own explanation to something that is _well-documented_. Also if it helps, the `G` in <kbd>^G</kbd> stands for `Go`.

Getting familiar to a keybind is a matter of habit and not remembering a keybind. `:wq` is not that simple to remember.

**Comment by maciejsum** [comment]
> What if a user (like me) has the variable set but (s)he doesn't want to end up into the last directory unless (s)he specifically indicates?

You won't. You only end up in this directory if you call `nnn` through a function like `n()` in `scripts/quitcd/`. If you call this function, you're already indicating that you want to use cd on quit, so from my point of view it is redundant to have to indicate it again while quitting.

If you call `nnn` directly and press the keybinding for 'quit and cd', it writes the last visited directory to `$NNN_TMPFILE`, but won't cd there. I see no harm in having this behaviour by default on every quit.

> I believe this is _well-documented_.

Sure it is. I had no problem understanding how it works, I would just prefer it to work slightly differently. But if you don't agree, I can simply patch it for myself - the program is so minimal that changing it to fit one's personal taste is easy :)

**Comment by jarun** [comment]
> You only end up in this directory if you call nnn through a function like n()

Exactly. I have that in my rc and I don't want to cd on quit every time. I like the brevity of having to type just `n` to start.

> I would just prefer it to work slightly differently

I would really appreciate that! Kindly share the patch if possible. There's another user who wanted that.

> the program is so minimal

And it would remain so. I plan to make the readline dep configurable too.

**Comment by jarun** [comment]
libreadline can now be dropped as per commit a8388ab60b0dda80002fa890a891d86e4fb440b0. The stock prompt would be used (no history or completion) but saves several KBs of memory at runtime.

**Comment by retipuj** [comment]
Is it possible to view the contents of the currently selected directory in an extra column without having to enter this directory (like the default in ranger, for example)? That would be a neat and very useful feature.

**Comment by jarun** [comment]
@retipuj sorry, `nnn` visual design would remain single-column.

**Comment by jarun** [comment]
Just to explain a bit more on the decision...

I think it's very evident from the README that the priority of `nnn` is to remain a lean and low resource/power consuming utility to navigate the filesystem and help with regular activities of people who have to spend a lot of time in the terminal but don't want to miss out on the GUI applications.

`nnn` uses _unfragmented_ memory in chunks to store information of files in the current dir. If it needs more it has to re-allocate because the amount of memory required cannot be determined beforehand.

Here's my `/usr`:

```
[1 2 3 4] /usr

 2019-02-22 05:56        /  bin/
 2018-10-21 08:47        /  games/
 2019-01-25 06:28        /  include/
 2019-02-10 17:10        /  lib/
 2018-11-03 18:16        /  lib32/
 2016-08-08 20:40        /  local/
 2019-02-22 05:56        /  sbin/
 2019-02-09 07:23        /  share/
 2019-02-02 14:39        /  src/
```

With the proposed interface, if a user wants to navigate to `/usr/share` he would have to load `/usr/bin` which on my system has 2078 files. This would need several consecutive re-allocations. How many files in `usr/share`? 288, which is roughly 9% of the memory that would get allocated.

That's not the end of it. He would also have to load 6 more directories making unnecessary disk accesses and wasting CPU time and power. He wouldn't even look into those!

Behind every design decision I make, there is a primary question - which purpose does it serve for the primary goal of the utility?

If I wanted to write a multi-pane file manager, I wouldn't have been using only ONE window in `nnn` so far - the default one. I would have added one for previewing files or images, one for side by side comparison of directories and so on... but there are plenty of file managers that do that.

Perhaps, when you consider enhancing the capabilities of `nnn`, think of `nnn` as an ISR, your extended use-case being the bottom half. You would probably appreciate what `nnn` delivers.
