### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#881]
Rolled from #781.

### Cooking

- [x] allow plugins to clear selection (#884, #889, #917)
- [x] do not clear selection on hovered file deletion
- [x] resurrect `'c'urrent/'s'el` prompt and option `-u` (#889)
- [x] more file/mime types supported in `preview-tui-ext`
- [x] plugin `mtpmount` - (un)mount MTP devices
- [x] plugin `cleanfilename` - more shell-friendly file names
- [x] plugin `rsynccp` - copy-paste with visual progress
- [x] replace `$HOME` by `~` in address bar
- [x] show current path in terminal title (#911)
- [x] total links and inode number of hardlink in statusbar
- [x] fix symlink to text file not opening in CLI editor (#890)
- [x] fix symlink size shown as 0B in statusbar (#888)
- [x] show symlink target in statusbar (#893)
- [x] show correct disk free/total on macOS (#888)
- [x] refactor printing entries in light/detail modes (#934)

### Up for grabs

- [ ] a light colorscheme with `NNN_FCOLORS`
- [ ] update only current context data when saving session (#837)
- [ ] generate static binary for arm, aarch with releases using CI (#623)
- [ ] support predefined filters like bookmarks
- [ ] open new terminal window in spawned shell directory (#759)

For anything else please discuss in this thread.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**

**Comment by KlzXS** [comment]
I've been thinking, it would be very nice if we could have separate documentation for every release in some form. Currently all documentation closely follows master, but many people just install whatever version is available in their repos. Then they try to follow the documentation provided here and run into issues. There have been several such issues raised in the past month, more than I feel there should be. 

I'd like to know what you think of this and any ideas for nicely implementing and maintaining it.

**Comment by jarun** [comment]
Generally our release notes captures the highlights. it's in the CHANGELOG too.

I think what you are looking for is something like buku - https://buku.readthedocs.io/en/latest/?badge=latest

However, that needs moving our Wiki to readthedocs and auto-updating when we change the wiki. Not sure how seamless the integration is.

**Comment by KlzXS** [comment]
Yes, I guess what buku uses is something akin to what I was thinking of, but with more work.

I know there's a changelog, but do you really read the changelog before or after the documentation?  I just wish it was a bit more accessible, that way it would hopefully lead to less people trying new things with old versions and then complaining when they don't work.

**Comment by KlzXS** [comment]
Also should we just implement some naive patch for persistent selection markers and then point people to that so they can compile it in themselves. That's also something I see repeated again and again.

It probably won't be very perfomant, there are going to be edge cases where it behaves in a way you didn't want it to, but you'll have it. Use at own risk.

**Comment by jarun** [comment]
> That's also something I see repeated again and again.

Why not limit selection to the directory? No other FM delivers what we do, if people are still not OK, why not just provide the usual?

**Comment by KlzXS** [comment]
No, don't limit the current functionality. I was thinking of just a patch to add to nnn. There was talk about having some user submitted patches listed, but nothing ever came out of that as far as I know.

**Comment by jarun** [comment]
We can do that. Please see if you can come up with something.

**Comment by luukvbaal** [comment]
Starting discussion on #919 here.
The PR implements the a new config variable `NNN_DCOLUMNS` allowing to change the order of the detail columns in detail mode. This results in e.g. the following detail modes:
Old situation on `master`:

![image](https://user-images.githubusercontent.com/31730729/112641488-bb856780-8e42-11eb-9856-4905092497dc.png)

`export NNN_DCOLUMNS=""`
![image](https://user-images.githubusercontent.com/31730729/112641792-fe473f80-8e42-11eb-91fe-bfd8ec8f0571.png)

`export NNN_DCOLUMNS="nsopt"`
![image](https://user-images.githubusercontent.com/31730729/112641913-1919b400-8e43-11eb-9d80-38abb858a590.png)

`export NNN_DCOLUMNS=nsoPt"`
![image](https://user-images.githubusercontent.com/31730729/112642006-2afb5700-8e43-11eb-820c-60fc9be45267.png)

**Comment by jarun** [comment]
When the name goes at the front and the length is 255 chars and it's a small terminal what happens to the other fields? Also, we like to keep config env variables minimum as well as checks int he code.

**Comment by luukvbaal** [comment]
This case is not handled yet, currently it just refuses to open the detail view. So is there any hope of it merging if cases such as that are handled properly? Or is a new config variable already a blocking factor.

**Comment by jarun** [comment]
The whole thing is a blocking factor. :)

I do not see any issue with the current order though it is fixed. I understand your case for flexibility. However, from my exp I remember a smartphone giant who exposed too many internals of SMS sending/receiving in the UI and no user could use it properly out of confusion. We have a fixed format and we are good as long as the information is correct.

**Comment by luukvbaal** [comment]
Don't quite get your user confusion point. As you can see without `NNN_DCOLUMNS` set it will just fall back to the default order and display the same information as on `master`(except size left aligned instead of right aligned).

**Comment by jarun** [comment]
I was giving an example of what happens when you give too many options to the users. As long as we can't confirm all permutations and combinations in languages including Chinese it is difficult to figure. We have a tool that has undergone 4 years of development and users are accustomed to the current interface. Is it necessary to have this?

**Comment by Kabouik** [comment]
Speaking of, as a simple user and regardless of the things @jarun is mentioning, I find your changes interesting byt I would prefer size to be right aligned. Units should always be right aligned in a table-like format in my opinion. It would even be best if `.00` could be added when there's no decimal so that the alignment is perfect, but this would probably clutter the view for just minimal benefits (*i.e.*, helping with my alignment OCD!).

**Comment by luukvbaal** [comment]
> I was giving an example of what happens when you give too many options to the users. As long as we can't confirm all permutations and combinations in languages including Chinese it is difficult to figure. We have a tool that has undergone 4 years of development and users are accustomed to the current interface. Is it necessary to have this?

And they will keep their accustomed interface if they don't define `NNN_DCOLUMNS`. Of course it's not necessary but I find the current detail view feels very wrong with the name as the last column. Especially when using icons.

**Comment by jarun** [comment]
Feel free to have a fork with the changes for yourself and others who prefer it.

**Comment by luukvbaal** [comment]
> It would even be best if `.0` could be added when there's no decimal so that the alignment is perfect, but this would probably clutter the view for limited benefits (_i.e._, helping with my alignment OCD and making size differences immediately evident, the latter may not be so negligible though).

I do agree with you there, having the decimals line up makes it more readable. I now have it looking like this:
![image](https://user-images.githubusercontent.com/31730729/112674115-d61d0800-8e65-11eb-8031-a12742aa7f16.png)

**Comment by Kabouik** [comment]
Ha! I might be one of those using your fork then! But I'm afraid a fork might be difficult to maintain on the long term, it's already hard enough for me to just keep up with with updating my local installation of nnn with the quick progress of `master`. :>

**Comment by luukvbaal** [comment]
> When the name goes at the front and the length is 255 chars and it's a small terminal what happens to the other fields? Also, we like to keep config env variables minimum as well as checks in the code.

Was able to fix this, `export NNN_DCOLUMNS="nsoPt; touch aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` now results in:
![image](https://user-images.githubusercontent.com/31730729/112704646-9f61e480-8e9b-11eb-9846-228c9d97c2c1.png)

The code quality probably isn't up to par since most of the alignment issues were fixed empirically so the logic is not clear in the code. However as far as I can tell no functional shortcomings remain, feel free to try it out [here](https://github.com/luukvbaal/nnn/tree/detail-columns)...

**Comment by luukvbaal** [comment]
Any interest in a PR to use `strftime()` for time printing? Honours env variable `TIME_STYLE` used by GNU `ls`.
Implemented in https://github.com/luukvbaal/nnn/commit/9ba1fbf65975037d958109c78c8c67077f0f9d90, would have to be adjusted somewhat for upstream `master`.

**Comment by luukvbaal** [comment]
BTW I don't see any issues with my detail column implementation: 
![demo](https://user-images.githubusercontent.com/31730729/112718631-93564100-8ef4-11eb-9029-93d0f6fe55bc.gif)
Curious to know whether it works properly on other locales as well which @jarun was worried about.

**Comment by Kabouik** [comment]
Just curious, did you test it with `n` as the last column and long file names too?

**Comment by luukvbaal** [comment]
Yeah works as it should on my end.

**Comment by luukvbaal** [comment]
> Feel free to have a fork with the changes for yourself and others who prefer it.

I'd rather not though. Preference can be defined in `NNN_DCOLUMNS`, that was the whole point.

It would be good to know what exactly keeps you from merging this feature. I don't want you to feel like I'm forcing this on you in your project so if you feel very strongly towards not merging this never mind... It's just that I'd rather not maintain a fork.

If increased binary size is the issue, how about another compile in option `COLUMNORDER`.

**Comment by jarun** [comment]
> It would be good to know what exactly keeps you from merging this feature.

@luukvbaal I have already mentioned reasons I don't want this in `nnn`. It's a 100 line change littered around for non-essential functionality. I don't see any great usability improvement either. The uid:gid column can be variable sized also. This is probably the 3rd/4th time I am telling I don't want it in and you are still continuing the discussion. If that's not persuading, what is? Hopefully, now you will realize what I meant when I told you to start the discussion first before implementing any big change. It saves everyone's time. I will not be able to respond to any other argument regarding this feature. Thanks for your understanding.

There's something that I would like to have regarding the columns though. @KlzXS brought it up once. If we can merge the two print functions that would be great. The first would print the details of an entry and the second would print the filename. But once again, it's not a top priority for any of us.

**Comment by luukvbaal** [comment]
Alright. Anyways the feature seemed essential to me hence why I implemented it...

For completeness: variable guid sizes were already considered and handled.

**Comment by ralphee** [comment]
> > 
> The uid:gid column can be variable sized also.

speaking of uid:gid; is there a way to only show a selection of files. Currently I have to comb through all the files (no biggie just want to make sure I have not missed the obvious).

**Comment by jarun** [comment]
Check plugin `uidgid`. Do something similar for selection.

**Comment by luukvbaal** [comment]
Potentially controversial change in https://github.com/jarun/nnn/pull/927, don't know if discussion is required?

**Comment by jarun** [comment]
Because of the current stage of the project we scrutinize a single extra line addition to the main program.
However, we are much more relaxed with scripts. :+1:

**Comment by jarun** [comment]
@luukvbaal can you work on a light colorscheme for `nnn` using `NNN_FCOLORS`? The default one we have today is intended for the dark.

**Comment by luukvbaal** [comment]
Never used a light theme so not sure how I would go white making one no.

**Comment by jarun** [comment]
No problem.

**Comment by jarun** [comment]
@0xACE I have taken care of the plugin framework changes to explicitly clear the selection.

@0xACE @KlzXS @Kabouik @leovilok @snide would it be possible to work on a light colorscheme for `nnn`?

**Comment by jarun** [comment]
@toddyamakawa as well for the light colorscheme.

**Comment by exoton** [comment]
> There's something that I would like to have regarding the columns though. @KlzXS brought it up once. If we can merge the two print functions that would be great. The first would print the details of an entry and the second would print the filename. But once again, it's not a top priority for any of us.

And I have just finished that. I'll submit a PR shortly.

**Comment by jarun** [comment]
> There are small differences in printing the filename in two modes that are now easy to spot (checking the detailed flag). I don't know if they were intentional or not.

Can you please add some more detail? What differences did you find?

**Comment by exoton** [comment]
It's actually just one difference in printing the soft link:
```
		if (!detailed && g_state.oldcolor)
			attrs |= A_DIM;
...
		if (detailed || !g_state.oldcolor)
			pair = (ent->flags & SYM_ORPHAN) ? C_ORP : C_LNK;


```

**Comment by jarun** [comment]
I think if we are in in 8-bit mode we still need to use A_DIM. What are we doing in 8-bit detail mode?

**Comment by exoton** [comment]
We don't change `attrs` in 8-bit detail mode. No A_DIM.

**Comment by jarun** [comment]
That may be because we dim the details, I think we should also dim the symlinks to retain the visual semblance with the light mode.

**Comment by exoton** [comment]
And what about the difference in the color pair? It's `0` in the 8-bit light mode and not `0` in the detail mode.
Please check the PR and request changes there.

**Comment by jarun** [comment]
Checking the PR and requesting changes there may not be possible because these were done long back and I don't remember every finer details there. So when you say there are differences I have to understand what they are from you and think accordingly.

**Comment by jarun** [comment]
Did the review. Please have a look.

**Comment by jarun** [comment]
Rolled at #935.
